-
  category: flour
  name: Atta
  type: (NISWIN)
  kg: 500kg Bag
-
  category: flour
  name: Atta
  type: (VMB)
  kg: 50kg Bag
-
  category: flour
  name: Atta
  type: (VMB)
  kg: 10kg Bag
-
  category: flour
  name: Atta
  type: (AMMAN)
  kg: 50kg Bag
-
  category: flour
  name: Maida
  type: (CHAVY PAROTTA)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (CHAVY BAKERY)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (VMB)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (VMB)
  kg: 10kg Bag 
-
  category: flour
  name: Maida
  type: (NISWIN)
  kg: 10kg Bag 
-
  category: flour
  name: Maida
  type: (APEX)
  kg: 10kg Bag
-
  category: flour
  name: Maida
  type: (ARASAN)
  kg: 10kg Bag 
-
  category: flour
  name: Maida
  type: (BANNARI PAROTA)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (BANNARI BAKERY)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (EVEREST)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (NISWIN)
  kg: 50kg Bag 
-
  category: flour
  name: Maida
  type: (VEGAM)
  kg: 50kg Bag 
-
  category: dal
  name: Orid Dal
  type: (WHITE UDASAL)
  kg: 50kg Bag 
-
  category: dal
  name: Orid Dal
  type: (KANNAN)
  kg: 50kg Bag 
-
  category: dal
  name: Orid Dal
  type: (NALAM)
  kg: 50kg Bag
-
  category: dal
  name: Orid Dal
  type: (MAHARAJA)
  kg: 10kg Bag  
-
  category: dal
  name: Orid Dhal
  type: (OM No 2)
  kg: 50kg Bag 
-
  category: dal
  name: Orid Dhal
  type: (BLACK UDASAL)
  kg: 50kg Bag
-
  category: dal
  name: Orid Dhal
  type: (AYYAN)
  kg: 50kg Bag
-
  category: dal
  name: Toor Dhal
  type: (KESAR GOLD)
  kg: 30kg Bag   
-
  category: dal
  name: Toor Dhal
  type: (MAAN)
  kg: 50kg Bag   
-
  category: dal
  name: Toor Dhal
  type: (FLYING HORSE)
  kg: 50kg Bag   
-
  category: dal
  name: Toor Dhal
  type: (KMS)
  kg: 50kg Bag   
-
  category: dal
  name: Toor Dhal
  type: (MAHARAJ)
  kg: 50kg Bag   
-
  category: dal
  name: Toor Dhal
  type: (SURIYA)
  kg: 50kg Bag   
-
  category: dal
  name: Orid Dhal
  type: (BLACK UDASAL) UN POLISH
  kg: 50kg Bag   
-
  category: pasi
  name: Pasi Payaru
  type: (APPLE)
  kg: 50kg Bag   
-
  category: pasi
  name: Pasi Payaru
  type: (GANAPATHI)
  kg: 50kg Bag     
-
  category: pasi
  name: Pasi Payaru
  type: (KALASH)
  kg: 50kg Bag   
-
  category: pasi
  name: Pasi Payaru
  type: (KARUDA)
  kg: 50kg Bag   
-
  category: pasi
  name: Pasi Payaru
  type: (SELLAKANI)
  kg: 50kg Bag   
-
  category: pasi
  name: Pasi Payaru
  type: (APPLE)
  kg: 30kg Bag   
-
  category: pasi
  name: Pasi Payir
  type: (AGT)
  kg: 25kg Bag 
-
  category: pasi
  name: Pasi Payir
  type: (100 LOT)
  kg: 5kg Bag 
-
  category: pasi
  name: Pasi Payir
  type: (NADU)
  kg: 50kg Bag 
-
  category: others
  name: Sugar
  type: (BANNARI)
  kg: 50kg Bag 
-
  category: others
  name: Sugar
  type: (MYLAR)
  kg: 50kg Bag
-
  category: others
  name: Sugar
  type: (SAKTHI)
  kg: 50kg Bag 
-
  category: others
  name: TATA SALT
  type: 
  kg: 1kg Bag  

 




